CREATE TABLE "TPL_DICT_CATEGORY" (
    "DICT_CATEGORY_ID" VARCHAR2(36) NOT NULL ENABLE,
    "NAME" VARCHAR2(255),
    "CODE" VARCHAR2(255),
    "PARENT" VARCHAR2(36),
    "IS_LEAF" NUMBER(1, 0),
    "DESCRIPTION" VARCHAR2(255),
    "CREATE_TIME" DATE,
    "CREATE_USER_ID" VARCHAR2(36),
    "MODIFY_USER_ID" VARCHAR2(36),
    "MODIFY_TIME" DATE,
    CONSTRAINT "PK_TPL_DICT_CATEGORY" PRIMARY KEY ("DICT_CATEGORY_ID")
);

COMMENT ON COLUMN "TPL_DICT_CATEGORY"."DICT_CATEGORY_ID" IS 'DICT_CATEGORY_ID';

COMMENT ON COLUMN "TPL_DICT_CATEGORY"."NAME" IS '字典类别名称';

COMMENT ON COLUMN "TPL_DICT_CATEGORY"."CODE" IS '字典类别编码';

COMMENT ON COLUMN "TPL_DICT_CATEGORY"."PARENT" IS '父节ID';

COMMENT ON COLUMN "TPL_DICT_CATEGORY"."IS_LEAF" IS '是否叶';

COMMENT ON COLUMN "TPL_DICT_CATEGORY"."DESCRIPTION" IS '描述';

COMMENT ON COLUMN "TPL_DICT_CATEGORY"."CREATE_TIME" IS '创建时间';

COMMENT ON COLUMN "TPL_DICT_CATEGORY"."CREATE_USER_ID" IS '创建人Id@AUTH_USER';

COMMENT ON COLUMN "TPL_DICT_CATEGORY"."MODIFY_USER_ID" IS '修改人id@AUTH_USER';

COMMENT ON COLUMN "TPL_DICT_CATEGORY"."MODIFY_TIME" IS '修改时间';

COMMENT ON TABLE "TPL_DICT_CATEGORY" IS '字典类别';