CREATE TABLE "AUTH_ROLE_PAGE" (
    "ROLE_PAGE_ID" VARCHAR2(36),
    "ROLE_ID" VARCHAR2(36),
    "PAGE_ID" VARCHAR2(36)
);

COMMENT ON COLUMN "AUTH_ROLE_PAGE"."ROLE_PAGE_ID" IS '主键';

COMMENT ON COLUMN "AUTH_ROLE_PAGE"."PAGE_ID" IS '页面Id';

COMMENT ON COLUMN "AUTH_ROLE_PAGE"."ROLE_ID" IS '角色Id';

COMMENT ON TABLE "AUTH_ROLE_PAGE" IS '角色拥有的页面权限';