CREATE TABLE "AUTH_PAGE" (
    "PAGE_ID" VARCHAR2(36) NOT NULL ENABLE,
    "NAME" VARCHAR2(255),
    "CODE" VARCHAR2(255),
    "PATH" VARCHAR2(255),
    "PARENT" VARCHAR2(36),
    "IS_LEAF" NUMBER(1),
    "ICON" VARCHAR2(255),
    "IS_HIDE" NUMBER(1),
    "IS_STOP" NUMBER(1),
    "INDEX_FIELD" NUMBER(10),
    "CREATE_TIME" DATE,
    "CREATE_USER_ID" VARCHAR2(36),
    "MODIFY_USER_ID" VARCHAR2(36),
    "MODIFY_TIME" DATE,
    CONSTRAINT "PK_AUTH_PAGE" PRIMARY KEY ("PAGE_ID")
);

COMMENT ON COLUMN "AUTH_PAGE"."PAGE_ID" IS 'PAGE_ID';

COMMENT ON COLUMN "AUTH_PAGE"."NAME" IS '页面名称';

COMMENT ON COLUMN "AUTH_PAGE"."CODE" IS '页面编码';

COMMENT ON COLUMN "AUTH_PAGE"."PATH" IS '访问路径';

COMMENT ON COLUMN "AUTH_PAGE"."PARENT" IS '父节ID';

COMMENT ON COLUMN "AUTH_PAGE"."IS_LEAF" IS '是否叶';

COMMENT ON COLUMN "AUTH_PAGE"."ICON" IS 'ICON';

COMMENT ON COLUMN "AUTH_PAGE"."IS_HIDE" IS '是否隐藏';

COMMENT ON COLUMN "AUTH_PAGE"."IS_STOP" IS '是否禁用';

COMMENT ON COLUMN "AUTH_PAGE"."INDEX_FIELD" IS '排序';

COMMENT ON COLUMN "AUTH_PAGE"."CREATE_TIME" IS '创建时间';

COMMENT ON COLUMN "AUTH_PAGE"."CREATE_USER_ID" IS '创建人Id@AUTH_USER';

COMMENT ON COLUMN "AUTH_PAGE"."MODIFY_USER_ID" IS '修改人id@AUTH_USER';

COMMENT ON COLUMN "AUTH_PAGE"."MODIFY_TIME" IS '修改时间';

COMMENT ON TABLE "AUTH_PAGE" IS '页面';