CREATE TABLE "AUTH_ROLE" (
    "ROLE_ID" VARCHAR2(36) NOT NULL ENABLE,
    "NAME" VARCHAR2(255),
    "CODE" VARCHAR2(255),
    "IS_STOP" NUMBER(1, 0),
    "DESCRIPTION" VARCHAR2(255),
    "CREATE_TIME" DATE,
    "CREATE_USER_ID" VARCHAR2(36),
    "MODIFY_USER_ID" VARCHAR2(36),
    "MODIFY_TIME" DATE,
    CONSTRAINT "PK_AUTH_ROLE" PRIMARY KEY ("ROLE_ID")
);

COMMENT ON COLUMN "AUTH_ROLE"."ROLE_ID" IS 'ROLE_ID';

COMMENT ON COLUMN "AUTH_ROLE"."NAME" IS '角色名称';

COMMENT ON COLUMN "AUTH_ROLE"."CODE" IS '角色编码';

COMMENT ON COLUMN "AUTH_ROLE"."IS_STOP" IS '是否停用';

COMMENT ON COLUMN "AUTH_ROLE"."DESCRIPTION" IS '描述';

COMMENT ON COLUMN "AUTH_ROLE"."CREATE_TIME" IS '创建时间';

COMMENT ON COLUMN "AUTH_ROLE"."CREATE_USER_ID" IS '创建人Id@AUTH_USER';

COMMENT ON COLUMN "AUTH_ROLE"."MODIFY_USER_ID" IS '修改人id@AUTH_USER';

COMMENT ON COLUMN "AUTH_ROLE"."MODIFY_TIME" IS '修改时间';

COMMENT ON TABLE "AUTH_ROLE" IS '系统角色';