CREATE TABLE "AUTH_ROLE_PAGE" (
    "ROLE_ID" VARCHAR2(36),
    "PAGE_ID" VARCHAR2(36)
);

COMMENT ON COLUMN "AUTH_ROLE_PAGE"."PAGE_ID" IS 'PAGE_ID';

COMMENT ON COLUMN "AUTH_ROLE_PAGE"."ROLE_ID" IS 'ROLE_ID';

COMMENT ON TABLE "AUTH_ROLE_PAGE" IS '角色拥有的页面权限';