CREATE TABLE "AUTH_ROLE_USER" (
    "ROLE_ID" VARCHAR2(36),
    "USER_ID" VARCHAR2(36),
    "CREATE_TIME" DATE,
    "CREATE_USER_ID" VARCHAR2(36),
    "MODIFY_USER_ID" VARCHAR2(36),
    "MODIFY_TIME" DATE,
);

COMMENT ON COLUMN "AUTH_ROLE_USER"."ROLE_ID" IS 'ROLE_ID';

COMMENT ON COLUMN "AUTH_ROLE_USER"."USER_ID" IS 'USER_ID';

COMMENT ON COLUMN "AUTH_ROLE_USER"."CREATE_TIME" IS '创建时间';

COMMENT ON COLUMN "AUTH_ROLE_USER"."CREATE_USER_ID" IS '创建人Id@AUTH_USER';

COMMENT ON COLUMN "AUTH_ROLE_USER"."MODIFY_USER_ID" IS '修改人id@AUTH_USER';

COMMENT ON COLUMN "AUTH_ROLE_USER"."MODIFY_TIME" IS '修改时间';