spring:
  datasource:
    url: jdbc:oracle:thin:@db/ORCLPDB1.localdomain
    username: atjob
    password: atjob
    driver-class-name: oracle.jdbc.OracleDriver

server:
  port: 9003
  tomcat:
    max-threads: 800
    uri-encoding: UTF-8
